name: GothamPhotoBeta
favicon: null
layout_spectrum: 0.8059552572667599
typography_spectrum: 0.32939161267131567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.19523183722048998
  lightness: 0.36421496188268065
  saturation: 0.3009782484732568
  rhythmicContrast: 0.6232160157524049
purpose: []
