name: GothamPhotoBeta
favicon: null
layout_spectrum: 0.05351
typography_spectrum: 0.53465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcdcde'
    - '#ab9e8b'
    - '#000002'
    - '#3b2d2c'
    - '#615c58'
  brandStrength: 1
  lightness: 0.36421496188268065
  saturation: 0.3009782484732568
  rhythmicContrast: 0.6232160157524049
purpose: []
